-- Oracle AI Database: Vector Search Basics
-- This script demonstrates how to create a table with vector columns, 
-- insert vector data, and perform similarity searches.

-- 1. Create a table with a VECTOR column
-- The 'VECTOR' data type is native to Oracle 23ai/26ai.
-- (3) represents the number of dimensions.
CREATE TABLE tech_articles (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR2(200),
    content     CLOB,
    v_content   VECTOR(3, FLOAT32) -- Example with 3 dimensions for simplicity
);

-- 2. Insert data with vectors
-- In a real scenario, vectors are generated via DBMS_VECTOR or an external LLM.
INSERT INTO tech_articles (title, content, v_content)
VALUES ('Oracle 26ai Overview', 'Exploring the new features of Oracle 26ai...', '[0.1, 0.8, 0.2]');

INSERT INTO tech_articles (title, content, v_content)
VALUES ('AI Agents in DB', 'How to build agents directly in the database...', '[0.2, 0.7, 0.3]');

INSERT INTO tech_articles (title, content, v_content)
VALUES ('Cooking Recipes', 'Best way to make a chocolate cake...', '[0.9, 0.1, 0.1]');

COMMIT;

-- 3. Perform a Similarity Search (Top-K)
-- Find the top 2 articles most similar to a query vector '[0.15, 0.75, 0.25]'
SELECT title, 
       VECTOR_DISTANCE(v_content, '[0.15, 0.75, 0.25]', COSINE) as distance
FROM tech_articles
ORDER BY distance
FETCH FIRST 2 ROWS ONLY;

-- 4. Create a Vector Index for performance
-- This is crucial for large datasets.
CREATE VECTOR INDEX v_idx_articles ON tech_articles(v_content) 
ORGANIZATION NEIGHBOR PARTITIONS
DISTANCE COSINE
WITH TARGET ACCURACY 95;
